### ISSUE TITLE
Loop through the java thing if playing singleplayer

### ISSUE THREAD

**Issue by NoLegitHere** [Mat1337/depression-client-issues#1]
here's the log: 

09:04:10 | l55nc | [OptiFine] (Reflector) Class not present: optifine.OptiFineClassTransformer
-- | -- | --
09:04:10 | l55nc | [OptiFine] *** Reflector Forge ***
09:04:10 | l55nc | [OptiFine] *** Reflector Vanilla ***
09:04:10 | g3nmy | LWJGL Version: 2.9.4
09:04:11 | l55nc | [OptiFine]
09:04:11 | l55nc | [OptiFine] OptiFine_1.8.8_HD_U_H8
09:04:11 | l55nc | [OptiFine] Build: null
09:04:11 | l55nc | [OptiFine] OS: Windows 7 (amd64) version 6.1
09:04:11 | l55nc | [OptiFine] Java: 1.8.0_51, Oracle Corporation
09:04:11 | l55nc | [OptiFine] VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
09:04:11 | l55nc | [OptiFine] LWJGL: 2.9.4
09:04:11 | l55nc | [OptiFine] OpenGL: Intel Bear Lake B, version 1.4.0 - Build 8.14.10.1930, Intel
09:04:11 | l55nc | [OptiFine] OpenGL Version: 1.4.0
09:04:11 | l55nc | [OptiFine] OpenGL Fancy fog: Not available (GL_NV_fog_distance)
09:04:11 | l55nc | [OptiFine] OpenGL Occlussion culling: Not available (GL_ARB_occlusion_query)
09:04:11 | l55nc | [OptiFine] Maximum texture size: 2048x2048
09:04:11 | l55nc | [OptiFine] Checking for new version
09:04:11 | hlz87 | [Shaders] ShadersMod version: 2.4.12
09:04:11 | hlz87 | [Shaders] OpenGL Version: 1.4.0 - Build 8.14.10.1930
09:04:11 | hlz87 | [Shaders] Vendor:  Intel
09:04:11 | hlz87 | [Shaders] Renderer: Intel Bear Lake B
09:04:11 | hlz87 | [Shaders] Capabilities:  -  -  -  -  -
09:04:11 | hlz87 | [Shaders] GL_MAX_DRAW_BUFFERS: 7
09:04:11 | hlz87 | [Shaders] GL_MAX_COLOR_ATTACHMENTS_EXT: 7
09:04:11 | hlz87 | [Shaders] GL_MAX_TEXTURE_IMAGE_UNITS: 16
09:04:11 | hlz87 | [Shaders] Load ShadersMod configuration.
09:04:11 | hlz87 | [Shaders] Save ShadersMod configuration.
09:04:11 | hlz87 | [Shaders] Shaders can not be loaded, Fast Render is enabled.
09:04:11 | hlz87 | [Shaders] No shaderpack loaded.
09:04:11 | b9tmv | Reloading ResourceManager: Default
09:04:11 | l55nc | [OptiFine] *** Reloading textures ***
09:04:11 | l55nc | [OptiFine] Resource packs: Default
09:04:12 | l55nc | [OptiFine] Version found: I7
09:04:12 | ozzx2 | Starting up SoundSystem...
09:04:12 | ozzx2 | Initializing LWJGL OpenAL
09:04:12 | ozzx2 | (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
09:04:12 | g3nmy | ########## GL ERROR ##########
09:04:12 | g3nmy | @ Pre startup
09:04:12 | g3nmy | 1281: Invalid value
09:04:15 | l55nc | [OptiFine] Mipmap levels: 4
09:04:15 | l55nc | [OptiFine] Multitexture: false
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/0_glass_white/glass_pane_white.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/0_glass_white/glass_white.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/10_glass_purple/glass_pane_purple.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/10_glass_purple/glass_purple.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/11_glass_blue/glass_blue.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/11_glass_blue/glass_pane_blue.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/12_glass_brown/glass_brown.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/12_glass_brown/glass_pane_brown.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/13_glass_green/glass_green.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/13_glass_green/glass_pane_green.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/14_glass_red/glass_pane_red.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/14_glass_red/glass_red.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/15_glass_black/glass_black.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/15_glass_black/glass_pane_black.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/1_glass_orange/glass_orange.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/1_glass_orange/glass_pane_orange.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/2_glass_magenta/glass_magenta.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/2_glass_magenta/glass_pane_magenta.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/3_glass_light_blue/glass_light_blue.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/3_glass_light_blue/glass_pane_light_blue.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/4_glass_yellow/glass_pane_yellow.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/4_glass_yellow/glass_yellow.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/5_glass_lime/glass_lime.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/5_glass_lime/glass_pane_lime.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/6_glass_pink/glass_pane_pink.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/6_glass_pink/glass_pink.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/7_glass_gray/glass_gray.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/7_glass_gray/glass_pane_gray.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/8_glass_silver/glass_pane_silver.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/8_glass_silver/glass_silver.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/9_glass_cyan/glass_cyan.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/9_glass_cyan/glass_pane_cyan.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/bookshelf.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/glass.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/glasspane.properties
09:04:15 | l55nc | [OptiFine] ConnectedTextures: mcpatcher/ctm/default/sandstone.properties
09:04:15 | l55nc | [OptiFine] Multipass connected textures: false
09:04:16 | un54w | Created: 1024x512 textures-atlas
09:04:17 | ozzx2 | OpenAL initialized.
09:04:17 | ozzx2 | Sound engine started
09:04:19 | l55nc | [OptiFine] *** Reloading custom textures ***
09:04:19 | l55nc | [OptiFine] Enable face culling: acacia_leaves, birch_leaves, dark_oak_leaves, jungle_leaves, oak_leaves, spruce_leaves
09:04:21 | g3nmy | ########## GL ERROR ##########
09:04:21 | g3nmy | @ Post render
09:04:21 | g3nmy | 1281: Invalid value
09:04:27 | dwjgb | Starting integrated minecraft server version 1.8.8
09:04:27 | dwjgb | Generating keypair
16:04:28 | game | java.lang.RuntimeException: Failed to instantiate class dko5k 	at ecvi8.y83ks(Unknown Source) 	at ehrog.g4vpz(Unknown Source) 	at dwjgb.f4zwv(Unknown Source) 	at dwjgb.a9w0w(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.NoSuchMethodException: dko5k.<init>(java.lang.String) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	... 6 more java.lang.RuntimeException: Failed to instantiate class dko5k 	at ecvi8.y83ks(Unknown Source) 	at z4lig.g4vpz(Unknown Source) 	at dwjgb.f4zwv(Unknown Source) 	at dwjgb.a9w0w(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.NoSuchMethodException: dko5k.<init>(java.lang.String) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	... 6 more java.lang.RuntimeException: Failed to instantiate class dko5k 	at ecvi8.y83ks(Unknown Source) 	at z4lig.g4vpz(Unknown Source) 	at dwjgb.f4zwv(Unknown Source) 	at dwjgb.a9w0w(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.NoSuchMethodException: dko5k.<init>(java.lang.String) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	... 6 more   <log4j:Event logger="zivjo" timestamp="1543629868083" level="INFO" thread="Server thread">     <log4j:Message><![CDATA[Preparing start region for level 0]]></log4j:Message>   </log4j:Event>
16:04:28 | monitor | expected <
09:04:28 | dwjgb | Changing view distance to 8, from 10
09:04:30 | u6_m0 | DiamondVN[local:E:f4bb4fd9] logged in with entity id 71 at (-993.740864167282, 4.0, -50.64972598591792)
09:04:30 | zivjo | DiamondVN joined the game
16:04:32 | game | java.lang.NoSuchMethodException: iwq8v.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: iwq8v.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: iwq8v.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: iwq8v.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: iwq8v.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: tfipp.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: iwq8v.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: iwq8v.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: iwq8v.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745)   <log4j:Event logger="dwjgb" timestamp="1543629871980" level="INFO" thread="Server thread">     <log4j:Message><![CDATA[Saving and pausing game...]]></log4j:Message>   </log4j:Event>
16:04:32 | monitor | expected <
09:04:31 | zivjo | Saving chunks for level 'New World'/Overworld
09:04:32 | zivjo | Saving chunks for level 'New World'/Nether
09:04:32 | zivjo | Saving chunks for level 'New World'/The End
09:06:04 | launcher | java.lang.NoSuchMethodException: iwq8v.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: tfipp.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: tfipp.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: tfipp.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: iwq8v.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: iwq8v.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: iwq8v.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: tfipp.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: tfipp.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: iwq8v.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: tfipp.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: tfipp.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: iwq8v.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: tfipp.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: tfipp.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: tfipp.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: iwq8v.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: iwq8v.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: kgv37.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: iwq8v.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: iwq8v.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: tfipp.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: tfipp.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: iwq8v.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: iwq8v.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: tfipp.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745) java.lang.NoSuchMethodException: iwq8v.<init>(iemnc) 	at java.lang.Class.getConstructor0(Class.java:3082) 	at java.lang.Class.getConstructor(Class.java:1825) 	at k0rjy.mgdae(Unknown Source) 	at ehrog.ahi5u(Unknown Source) 	at qtg6s.ahi5u(Unknown Source) 	at zivjo.iotg1(Unknown Source) 	at zivjo.t3af0(Unknown Source) 	at dwjgb.t3af0(Unknown Source) 	at zivjo.run(Unknown Source) 	at java.lang.Thread.run(Thread.java:745)
16:06:04 | monitor | Process crashed with exit code -1073741819

**Comment by Mat1337** [comment]
Issue fixed, go ahead and re-download the client from the website and you should be fine
